
gen state_abrev = "AL" if est_st == 1
replace state_abrev = "AK" if est_st == 2
replace state_abrev = "AZ" if est_st == 4
replace state_abrev = "AR" if est_st == 5
replace state_abrev = "CA" if est_st == 6
replace state_abrev = "CO" if est_st == 8
replace state_abrev = "CT" if est_st == 9
replace state_abrev = "DE" if est_st == 10
replace state_abrev = "DC" if est_st == 11
replace state_abrev = "FL" if est_st == 12
replace state_abrev = "GA" if est_st == 13
replace state_abrev = "HI" if est_st == 15
replace state_abrev = "ID" if est_st == 16
replace state_abrev = "IL" if est_st == 17
replace state_abrev = "IN" if est_st == 18
replace state_abrev = "IA" if est_st == 19
replace state_abrev = "KS" if est_st == 20
replace state_abrev = "KY" if est_st == 21
replace state_abrev = "LA" if est_st == 22
replace state_abrev = "ME" if est_st == 23
replace state_abrev = "MD" if est_st == 24
replace state_abrev = "MA" if est_st == 25
replace state_abrev = "MI" if est_st == 26
replace state_abrev = "MN" if est_st == 27
replace state_abrev = "MS" if est_st == 28
replace state_abrev = "MO" if est_st == 29
replace state_abrev = "MT" if est_st == 30
replace state_abrev = "NE" if est_st == 31
replace state_abrev = "NV" if est_st == 32
replace state_abrev = "NH" if est_st == 33
replace state_abrev = "NJ" if est_st == 34
replace state_abrev = "NM" if est_st == 35
replace state_abrev = "NY" if est_st == 36
replace state_abrev = "NC" if est_st == 37
replace state_abrev = "ND" if est_st == 38
replace state_abrev = "OH" if est_st == 39
replace state_abrev = "OK" if est_st == 40
replace state_abrev = "OR" if est_st == 41
replace state_abrev = "PA" if est_st == 42
replace state_abrev = "RI" if est_st == 44
replace state_abrev = "SC" if est_st == 45
replace state_abrev = "SD" if est_st == 46
replace state_abrev = "TN" if est_st == 47
replace state_abrev = "TX" if est_st == 48
replace state_abrev = "UT" if est_st == 49
replace state_abrev = "VT" if est_st == 50
replace state_abrev = "VA" if est_st == 51
replace state_abrev = "WA" if est_st == 53
replace state_abrev = "WV" if est_st == 54
replace state_abrev = "WI" if est_st == 55
replace state_abrev = "WY" if est_st == 56
